const randomText = document.querySelector('#random-text');
const randomTextBtn = document.querySelector('#random-text-btn');

function randomizeText() {
	let Text = ['Ha az Ön vállalkozása a művészet és kultúra rétegéhez tartozik, biztosan tudja, hogy kifejezetten fontos az, hogy a weboldala magas minőségű vizuális tartalommal rendelkezzen. Ha Ön egy DJ, művész, festő vagy egy honlapra van szüksége a szolgáltatásai, film előfizetések, színház jegyvásárlás vagy hasonló tevékenységek számára. Eljött az idő, hogy egy professzionális online jelenlétet teremtsen a weboldala számára.', 
			'A <a href=”https://www.templatemonster.com/hu/kategoria/muveszet-kultura-wordpress-temak/”>Művészeti témák</a>  a különböző típusú művészeti stílusokat egészítik ki. Minden sablon könnyen testreszabható, legyen ez egy művészeti blog, iskola vagy galéria. Válasszon a semleges tervezések a fényesebb alkotások bemutatására vagy az élénkebb vektoros témák között. Minden illusztrációs WordPress téma hivatásos webfejlesztők által a legújabb webes technológiák segítségével lett létrehozva. Abban az esetben, ha egy hivatásos tervezésre van szüksége egy teljeskörű művészeti közösség létrehozásához, lehetősége lesz a digitális művészet közösség <a href=”https://www.templatemonster.com/hu/wordpress-sablonok/”>WordPress sablonok</a> között választani.',
			 'Egy zenebolt, blog, felvételi stúdió, portál számára szeretne WordPress témát? Vessen egy pillantást a TemplateMonster által kínált legjobb WordPress Zenei témákra.', 
			 'A múzeumok mindig inspirálták az érdeklődést a történelmi tények iránt, de manapság már elkerülik őket az emberek. Annak éredekében, hogy feltámassza a múzeumok iránti szenvedélyt, eljött az idő, hogy a tudást ott terjessze, ahol a legtöbb ember mostanában megtalálható: online. Az érdekes információk kiváló képekkel és fantasztikus színsémákkal lesznek támogatva. Nem számít, hogy egy történelmi vagy írói múzeumot szeretne előmozdítani - használja a WordPress sablonokat a céljai eléréséhez!', 
			 'Ha az olyan filmportál, amely évre/műfajra/értékelésre csoportosítja a filmeket, elég sok problémát okoz, vessen egy pillantást az előre elkészített dizájnokra, amelyek a Filmes WordPress gyűjteményben találhatók meg. Itt Ön olyan dizájnokat találhat, amelyek ideálisan megfelelnek a tartalomban gazdag weboldalak számára: film streaming portálok és blogok. A Filmes WordPress témák elrendezése egy fejlett oszlopstruktúrával rendelkezik, amely minden információt egy tiszta, érthető módon jelenít meg.', 
			 'Úgy tűnik, Önt a színház üzleti része érdekli. Ebben az esetben nem kell megmagyarázni, hogy mennyire nehéz manapság a színházi darabok hirdetése. Mint minden niche tevékenységnél, az online jelenlét egy fontos tényező, ami minden üzlet életképességét jelentősen befolyásolja.', 
			 'A művészeti galériák a művészeti élményekről szólnak. Ha Ön ebben az üzletben tevékenykedik, biztosan tudja, hogy mennyire fontos az, hogy a portfóliója minél több ember által legyen felfedezve. A mai naptól ez is lehetséges, mivel az egyszerű galéria sablonoknál sokkal többet nyújtunk!', 
			 'A művészet, rajzolás tanítása önmagában is gyönyörű kihívás lehet. De, ha Ön azt szeretné. hogy az Ön művészeti iskolája vagy akadémiája új diákokat ést résztvevőket vonzzon, egy kiváló online jelenlétet kell kínálnia. A művészet a látványról szól. Egy lehetőséget kell teremteni az embereknek, hogy azok azt a megfelelő módon tapasztalják meg.', 
			 'A művészet egy olyan médium, amely kommunikál az emberekkel. Az vagy a művész vízióját képviseli, vagy képes arra, hogy az emberek kifejezzék az érzelmeiket. De egy dolog biztos - a művészet egy vizuális élmény. Ezért is fontos az, hogy helyesen legyen bemutatva. Az online jelenlét sokat mondhat a művészről, de elég nehéz egy olyan weboldalt készíteni, amely kiegészítené a művészeti alkotásokat.', 'A nyomtatási technológiák gyorsan fejlődnek. A mai világban, ha Ön egy nyomdaipari vállalkozásnak a tulajdonosa, meg kell mutatnia a potenciális ügyfeleknek, hogy Ön könnyen alkalmazkodik az új technológiák kihívásához.'];
	randomText.value = Text[Math.floor(Math.random() * 10)];
}; 

randomTextBtn.addEventListener('click', randomizeText);